#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
# export PATH="$HOME/.local/bin":$PATH


# EXA Colors


export EXA_ICON_SPACING=2
# files, dirs, links, executables, links with not target
clr="reset:ex=33;01:di=33:ln=04;35:or=33:lp=35:fi=00"

# user permission bits
clr=$clr":ur=00:uw=00:ux=33;01:ue=00"

# group
clr=$clr":gr=00:gw=00:gx=00"

# others
clr=$clr":tr=00:tw=00:tx=00"

# filesize number and color < 1KB
clr=$clr":nb=00:ub:00"

#  1KB < size < 1MB
clr=$clr":nk=00;01:uk=00;01"

# 1 MB < size < 1 GB
clr=$clr":nm=33:um=33"

# 1 GB < size < 1 TB
clr=$clr":ng=33:ug=35"

# git
clr=$clr":ga=33;01:gm=32;01:gd=31;01:gv=38;5;226"

# date, user 
clr=$clr":da=0:uu=33"


# markdow
clr=$clr":*.md=00:README.md=38;5;226;04"

export EXA_COLORS=$clr
