return {

  -- PATCH_OPEN
Normal = {fg = "#B3ACD8", bg = "#4C417C"},
Boolean = {},
Character = {},
Comment = {fg = "#6D6C84"},
Conceal = {},
Conditional = {fg = "#955ED4"},
Constant = {},
CursorColumn = {bg = "#443A6E"},
CursorLine = {bg = "#443A6E"},
CursorLineNr = {fg = "#F7BA2B", bg = "#443A6E"},
DiagnosticError = {fg = "#A3001B", bold = true},
DiagnosticHint = {fg = "#7899F2", bold = true},
DiagnosticInfo = {fg = "#B9C398", bold = true},
DiagnosticWarn = {fg = "#FF8D29", bold = true},
Directory = {fg = "#A364A6"},
EndOfBuffer = {fg = "#FF0000"},
Error = {fg = "#000000", bg = "#FF0000"},
ErrorMsg = {fg = "#000000", bg = "#FF0000"},
Float = {},
Folded = {fg = "#000000", bg = "#87C92C"},
Function = {fg = "#34B431", bold = true},
HorizSplit = {fg = "#F7BA2B"},
Identifier = {fg = "#51CF4F"},
LineNr = {fg = "#6A5CB2"},
LspCodeLens = {},
LspCodeLensSeparator = {},
LspReferenceRead = {},
LspReferenceText = {},
LspReferenceWrite = {},
LspSignatureActiveParameter = {},
LualineCommand = {fg = "#4C417C", bg = "#FF8D29"},
LualineInactive = {fg = "#8478BF", bg = "#47345B"},
LualineInsert = {fg = "#2D2749", bg = "#51CF4F"},
LualineNormal = {fg = "#B3ACD8", bg = "#775798"},
LualineReplace = {fg = "#B3ACD8", bg = "#4C417C"},
LualineVisual = {fg = "#2D2749", bg = "#A979C8"},
NormalFloat = {},
Number = {},
NvimTreeClosedFolderIcon = {fg = "#864E88"},
NvimTreeExecFile = {fg = "#A4DA58"},
NvimTreeFolderIcon = {fg = "#A364A6"},
NvimTreeGitDirty = {fg = "#A4DA58"},
NvimTreeGitIgnored = {fg = "#000000"},
NvimTreeGitNew = {fg = "#FFFFFF"},
NvimTreeGitStaged = {fg = "#A4DA58", bold = true, italic = true},
NvimTreeOpenedFolderIcon = {fg = "#B887BA"},
NvimTreeOpenedFolderName = {fg = "#B887BA"},
NvimTreeRootFolder = {fg = "#A364A6", bold = true, underline = true},
NvimTreeSymlink = {fg = "#F7BA2B"},
ObsBold = {bold = true},
ObsBoldItalics = {bold = true, italic = true},
ObsCalloutAbstract = {bold = true},
ObsCalloutAttention = {bold = true},
ObsCalloutBug = {bold = true},
ObsCalloutCaution = {bold = true},
ObsCalloutCheck = {bold = true},
ObsCalloutCite = {bold = true},
ObsCalloutDanger = {bold = true},
ObsCalloutDone = {bold = true},
ObsCalloutError = {bold = true},
ObsCalloutExample = {bold = true},
ObsCalloutFail = {bold = true},
ObsCalloutFailure = {bold = true},
ObsCalloutFaq = {bold = true},
ObsCalloutHeadline = {},
ObsCalloutHelp = {bold = true},
ObsCalloutHint = {bold = true},
ObsCalloutImportant = {bold = true},
ObsCalloutInfo = {bold = true},
ObsCalloutMissing = {bold = true},
ObsCalloutNote = {bold = true},
ObsCalloutQuestion = {bold = true},
ObsCalloutQuote = {bold = true},
ObsCalloutSuccess = {bold = true},
ObsCalloutSummary = {bold = true},
ObsCalloutTip = {bold = true},
ObsCalloutTitle = {bold = true},
ObsCalloutTldr = {bold = true},
ObsCalloutTodo = {bold = true},
ObsCalloutWarning = {bold = true},
ObsH1 = {fg = "#D45E62", bg = "#4C417C", bold = true},
ObsH2 = {fg = "#D05ED4", bg = "#4C417C", bold = true},
ObsH3 = {fg = "#955ED4", bg = "#4C417C", bold = true},
ObsH4 = {fg = "#6E5ED4", bg = "#4C417C", bold = true},
ObsH5 = {fg = "#8B7EDD", bg = "#4C417C", bold = true},
ObsItalics = {italic = true},
ObsLinkDest = {fg = "#51CF4F", bg = "#4C417C", underline = true},
ObsLinkName = {fg = "#84DD83", bg = "#4C417C", underline = true},
ObsLinkNoRename = {fg = "#84DD83", bg = "#4C417C", underline = true},
ObsLinkRename = {fg = "#84DD83", bg = "#4C417C", underline = true},
ObsPyBlockDelim = {fg = "#7CCF4F", bg = "#000000", bold = true},
ObsSingleTicks = {bg = "#262626"},
ObsTag = {fg = "#4C417C", bg = "#D16200"},
ObsTextBlockRef = {fg = "#B3B3B3", bg = "#443A6E", italic = true},
ObsTriTicksDelim = {fg = "#7CCF4F", bg = "#000000", bold = true},
ObsYamlFM = {fg = "#9A90CB", bg = "#584C90"},
Pmenu = {bg = "#443A6E"},
PmenuSbar = {fg = "#000000", bg = "#E2A108"},
PmenuSel = {bg = "#584C90"},
PmenuThumb = {fg = "#000000", bg = "#87C92C"},
PreProc = {fg = "#00DB00", bold = true},
Search = {fg = "#000000", bg = "#00DB00"},
SignColumn = {bg = "#443A6E"},
Statement = {fg = "#955ED4"},
String = {fg = "#C58C07", italic = true},
TabLine = {fg = "#B3ACD8", bg = "#4C417C"},
TabLineFill = {},
TexLink = {bold = true},
Type = {fg = "#00FF00"},
Underlined = {fg = "#7899F2", underline = true},
VertSplit = {fg = "#F7BA2B"},
Visual = {fg = "#333333", bg = "#A4DA58", italic = true, reverse = true},
Whitespace = {bg = "#000000"},
Winseparator = {fg = "#FF8D29"},
  -- PATCH_CLOSE

}
