#!/usr/bin/env bash

## Author  : Aditya Shakya
## Mail    : adi1090x@gmail.com
## Github  : @adi1090x
## Twitter : @adi1090x

# Available Styles
# >> Created and tested on : rofi 1.6.0-1
#
# style_1     style_2     style_3     style_4     style_5     style_6
# style_7     style_8     style_9     style_10    style_11    style_12

theme="style_1"

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

dir=$dir/colorful

echo $dir

# dark
ALPHA="#00000000"
BG="#775899"
FG="#000000"
SELECT="#7573A3"
SIDE="#ff8c28"
ACCENT="#54CF51"

# overwrite colors file
cat > $dir/colors.rasi <<- EOF
	/* colors */

	* {
	  al:   $ALPHA;
	  bg:   $BG;
	  se:   $SELECT;
	  fg:   $FG;
	  ac:   $ACCENT;
    sen:  $SIDE;
	}
EOF

# comment these lines to disable random style
themes=($(ls -p --hide="colors.rasi" $dir))
theme="${themes[$(( $RANDOM % 5 ))]}"
# theme="${themes[4]}"

rofi -no-lazy-grab -show windowcd -modi windowcd -theme $dir/"$theme"
# rofi -no-lazy-grab -show windowcd -modi windowcd -kb-row-down 'Alt+Tab' -kb-row-up 'Alt+ISO_Left_Tab' -kb-accept-entry '!Alt_L,!Alt+Tab' -theme $dir/"$theme"
