require "main.options"
require "main.keymaps"
require "main.plugins"
require "main.autopairs"
require "main.nvim-tree"
require "main.telescope"
require "main.bufferline"
require "main.cmp"
require "main.colorscheme"
require "main.colorizer"
require "main.lightspeed"
require "main.lsp"
require "main.gitsigns"
require "main.vimtex"
require "main.toggleterm"
require "main.luasnip"
require "main.which-key"
require "main.treesitter"
require "main.vgit"
require "main.vimwiki"
-- require "main.nvim-markdown"
-- require "main.telekasten"
require "main.comments"
require "main.autocmd"
require "main.lualine"
require "main.matchup"
require "main.surround"
require "main.pretty-fold"
require "main.fold-preview"
require "main.workspaces"
require "main.todo-comments"

-- TODO: check gisigns vs vgit
