-- vim.cmd[[set matchpairs+=':']]
vim.cmd[[let g:matchup_transmute_enabled = 1]]
vim.cmd[[let g:matchup_surround_enabled = 1]]
vim.cmd[[let g:matchup_matchparen_offscreen = {'method': 'popup'}]]
-- vim.cmd[[autocmd FileType vimwiki let g:matchup_override_vimtex = 1]]
